<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Roberto_Antuna">
<meta name="dcterms.date" content="2026-02-02">

<title>Cyclistic Bike-Share Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-4d7f0bce1131f3e5f9547cd857cfbfc8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#ask" id="toc-ask" class="nav-link" data-scroll-target="#ask">1. Ask</a>
  <ul class="collapse">
  <li><a href="#business-task" id="toc-business-task" class="nav-link" data-scroll-target="#business-task">Business Task</a></li>
  <li><a href="#key-stakeholders" id="toc-key-stakeholders" class="nav-link" data-scroll-target="#key-stakeholders">Key Stakeholders</a></li>
  <li><a href="#primary-question" id="toc-primary-question" class="nav-link" data-scroll-target="#primary-question">Primary Question</a></li>
  <li><a href="#a-bonus-chapter-real-time-membership-offers" id="toc-a-bonus-chapter-real-time-membership-offers" class="nav-link" data-scroll-target="#a-bonus-chapter-real-time-membership-offers">A Bonus Chapter: Real-Time Membership Offers</a></li>
  </ul></li>
  <li><a href="#ndefinedprepare" id="toc-ndefinedprepare" class="nav-link" data-scroll-target="#ndefinedprepare">2. ndefinedPrepare</a>
  <ul class="collapse">
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources">Data Sources</a></li>
  <li><a href="#data-credibility-roccc-analysis" id="toc-data-credibility-roccc-analysis" class="nav-link" data-scroll-target="#data-credibility-roccc-analysis">Data Credibility (ROCCC Analysis)</a></li>
  <li><a href="#data-integrity-privacy" id="toc-data-integrity-privacy" class="nav-link" data-scroll-target="#data-integrity-privacy">Data Integrity &amp; Privacy</a></li>
  </ul></li>
  <li><a href="#process" id="toc-process" class="nav-link" data-scroll-target="#process">3. Process</a>
  <ul class="collapse">
  <li><a href="#setup-and-data-import" id="toc-setup-and-data-import" class="nav-link" data-scroll-target="#setup-and-data-import">3.1 Setup and Data Import</a></li>
  <li><a href="#data-inspection" id="toc-data-inspection" class="nav-link" data-scroll-target="#data-inspection">3.2 Data Inspection</a></li>
  <li><a href="#column-standardization" id="toc-column-standardization" class="nav-link" data-scroll-target="#column-standardization">3.3 Column Standardization</a></li>
  <li><a href="#data-consistency-type-conversion" id="toc-data-consistency-type-conversion" class="nav-link" data-scroll-target="#data-consistency-type-conversion">3.4 Data Consistency &amp; Type Conversion</a></li>
  <li><a href="#merging-datasets" id="toc-merging-datasets" class="nav-link" data-scroll-target="#merging-datasets">3.5 Merging Datasets</a></li>
  <li><a href="#adding-time-metrics" id="toc-adding-time-metrics" class="nav-link" data-scroll-target="#adding-time-metrics">3.6 Adding Time Metrics</a></li>
  <li><a href="#data-cleaning-and-validation" id="toc-data-cleaning-and-validation" class="nav-link" data-scroll-target="#data-cleaning-and-validation">3.7 Data Cleaning and Validation</a></li>
  <li><a href="#station-name-standardization" id="toc-station-name-standardization" class="nav-link" data-scroll-target="#station-name-standardization">3.8 Station Name Standardization</a></li>
  <li><a href="#coordinate-enrichment-backfilling" id="toc-coordinate-enrichment-backfilling" class="nav-link" data-scroll-target="#coordinate-enrichment-backfilling">3.9 Coordinate Enrichment (Backfilling)</a></li>
  <li><a href="#final-data-type-transformation" id="toc-final-data-type-transformation" class="nav-link" data-scroll-target="#final-data-type-transformation">3.10 Final Data Type Transformation</a></li>
  <li><a href="#final-column-selection" id="toc-final-column-selection" class="nav-link" data-scroll-target="#final-column-selection">3.11 Final Column Selection</a></li>
  <li><a href="#data-health-check-quality-assurance" id="toc-data-health-check-quality-assurance" class="nav-link" data-scroll-target="#data-health-check-quality-assurance">3.12 Data Health Check &amp; Quality Assurance</a></li>
  <li><a href="#outlier-treatment-business-logic-validation" id="toc-outlier-treatment-business-logic-validation" class="nav-link" data-scroll-target="#outlier-treatment-business-logic-validation">3.13 Outlier Treatment &amp; Business Logic Validation</a></li>
  </ul></li>
  <li><a href="#analyze" id="toc-analyze" class="nav-link" data-scroll-target="#analyze">4. Analyze</a>
  <ul class="collapse">
  <li><a href="#general-descriptive-statistics" id="toc-general-descriptive-statistics" class="nav-link" data-scroll-target="#general-descriptive-statistics">4.1 General Descriptive Statistics</a></li>
  <li><a href="#segmented-analysis-members-vs.-casuals" id="toc-segmented-analysis-members-vs.-casuals" class="nav-link" data-scroll-target="#segmented-analysis-members-vs.-casuals">4.2 Segmented Analysis: Members vs.&nbsp;Casuals</a></li>
  <li><a href="#weekly-usage-patterns" id="toc-weekly-usage-patterns" class="nav-link" data-scroll-target="#weekly-usage-patterns">4.3 Weekly Usage Patterns</a></li>
  <li><a href="#hourly-usage-patterns" id="toc-hourly-usage-patterns" class="nav-link" data-scroll-target="#hourly-usage-patterns">4.4 Hourly Usage Patterns</a></li>
  <li><a href="#geographic-analysis-top-starting-stations-by-user-type" id="toc-geographic-analysis-top-starting-stations-by-user-type" class="nav-link" data-scroll-target="#geographic-analysis-top-starting-stations-by-user-type">4.5 Geographic Analysis: Top Starting Stations by User Type</a></li>
  </ul></li>
  <li><a href="#share-visualization" id="toc-share-visualization" class="nav-link" data-scroll-target="#share-visualization">5. Share (Visualization)</a>
  <ul class="collapse">
  <li><a href="#average-ride-duration-the-leisure-gap" id="toc-average-ride-duration-the-leisure-gap" class="nav-link" data-scroll-target="#average-ride-duration-the-leisure-gap">5.1 Average Ride Duration (The Leisure Gap)</a></li>
  <li><a href="#user-distribution-by-day-proportional-analysis" id="toc-user-distribution-by-day-proportional-analysis" class="nav-link" data-scroll-target="#user-distribution-by-day-proportional-analysis">5.2 User Distribution by Day (Proportional Analysis)</a></li>
  <li><a href="#hourly-distribution-per-day-the-commuter-pulse" id="toc-hourly-distribution-per-day-the-commuter-pulse" class="nav-link" data-scroll-target="#hourly-distribution-per-day-the-commuter-pulse">5.3 Hourly Distribution per Day (The Commuter Pulse)</a></li>
  <li><a href="#geographic-distribution-mapping-the-two-worlds" id="toc-geographic-distribution-mapping-the-two-worlds" class="nav-link" data-scroll-target="#geographic-distribution-mapping-the-two-worlds">5.4 Geographic Distribution (Mapping the Two Worlds)</a></li>
  <li><a href="#geographic-cluster-map-the-spatial-divide" id="toc-geographic-cluster-map-the-spatial-divide" class="nav-link" data-scroll-target="#geographic-cluster-map-the-spatial-divide">5.5 Geographic Cluster Map (The Spatial Divide)</a></li>
  </ul></li>
  <li><a href="#act-recommendations" id="toc-act-recommendations" class="nav-link" data-scroll-target="#act-recommendations">6. Act (Recommendations)</a>
  <ul class="collapse">
  <li><a href="#localized-leisure-corridor-campaigns" id="toc-localized-leisure-corridor-campaigns" class="nav-link" data-scroll-target="#localized-leisure-corridor-campaigns">6.1 Localized “Leisure Corridor” Campaigns</a></li>
  <li><a href="#the-weekend-warrior-membership-tier" id="toc-the-weekend-warrior-membership-tier" class="nav-link" data-scroll-target="#the-weekend-warrior-membership-tier">6.2 The “Weekend Warrior” Membership Tier</a></li>
  <li><a href="#off-peak-afternoon-incentives" id="toc-off-peak-afternoon-incentives" class="nav-link" data-scroll-target="#off-peak-afternoon-incentives">6.3 Off-Peak Afternoon Incentives</a></li>
  </ul></li>
  <li><a href="#bonus-chapter-predictive-modeling-for-conversion-from-casual-insights-to-real-time-membership-offers" id="toc-bonus-chapter-predictive-modeling-for-conversion-from-casual-insights-to-real-time-membership-offers" class="nav-link" data-scroll-target="#bonus-chapter-predictive-modeling-for-conversion-from-casual-insights-to-real-time-membership-offers">Bonus Chapter: Predictive Modeling for Conversion — From Casual Insights to Real-Time Membership Offers</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Cyclistic Bike-Share Analysis</h1>
<p class="subtitle lead">Google Data Analytics Capstone</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Roberto_Antuna </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 2, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Cyclistic is a fictional company launched in Chicago in 2016. The company specializes in providing residents with bicycles for use within the city. Currently, they have more than <strong>5,800 bicycles</strong> and more than <strong>650 docking stations</strong>.</p>
<p>Cyclistic offers flexible plans for utilizing their equipment:</p>
<ul>
<li>Single-ride pass<br>
</li>
<li>Full-day pass<br>
</li>
<li>Annual membership</li>
</ul>
<p>The first two categories are considered <strong><em>Casual riders</em></strong> (Customers according to the records), while the third category consists of <strong><em>Cyclistic members</em></strong> (Subscribers according to the records).</p>
<p>In addition to conventional bicycles, Cyclistic provides three inclusive options:</p>
<div class="quarto-layout-panel" data-layout-ncol="3" style="text-align: center;">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/reclining_bike.png" class="img-fluid figure-img" alt="Reclining Bike"></p>
<figcaption>Image 1. Reclining Bikes</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/hand_tricycle.png" class="img-fluid figure-img" alt="Hand Tricycle"></p>
<figcaption>Image 2. Hand Tricycles</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/cargo_bike.png" class="img-fluid figure-img" alt="Cargo Bike"></p>
<figcaption>Image 3. Cargo Bikes</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>The marketing analyst team, led by Director Lily Moreno, has identified that 92% of users utilize conventional bicycles. Furthermore, 70% of users use the equipment for recreational purposes, while the remaining 30% use it as a means of transportation to work.</p>
<p>Given that annual memberships yield the highest profits, the marketing team aims to better understand users, their needs, and attraction channels (digital media) to <strong>convert casual riders into Cyclistic members</strong>.</p>
<div class="quarto-layout-panel" data-layout-ncol="1" style="text-align: center;">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/cyclistic.png" class="img-fluid figure-img" alt="Cyclistic logo"></p>
<figcaption>Image 4. Cyclistic</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="ask" class="level2">
<h2 class="anchored" data-anchor-id="ask">1. Ask</h2>
<section id="business-task" class="level3">
<h3 class="anchored" data-anchor-id="business-task">Business Task</h3>
<p>The primary objective of this analysis is to identify key differences in how annual members and casual riders utilize Cyclistic’s bike-share service. By extracting these insights from historical trip data, I aim to provide data-driven recommendations for a marketing strategy specifically designed to convert casual riders into long-term annual members, thereby driving sustainable growth for the company.</p>
</section>
<section id="key-stakeholders" class="level3">
<h3 class="anchored" data-anchor-id="key-stakeholders">Key Stakeholders</h3>
<ul>
<li><strong>Lily Moreno:</strong> Director of Marketing and my manager. She is responsible for the development of campaigns and initiatives to promote the bike-share program.</li>
<li><strong>Cyclistic Marketing Analytics Team:</strong> A team of data analysts who are responsible for collecting, analyzing, and reporting data that helps guide Cyclistic’s marketing strategy.</li>
<li><strong>Cyclistic Executive Team:</strong> The notoriously detail-oriented executive team who will decide whether to approve the recommended marketing program.</li>
</ul>
</section>
<section id="primary-question" class="level3">
<h3 class="anchored" data-anchor-id="primary-question">Primary Question</h3>
<p>To guide the marketing strategy, this report focuses on answering:<br>
<strong>How do annual members and casual riders use Cyclistic bikes differently?</strong></p>
</section>
<section id="a-bonus-chapter-real-time-membership-offers" class="level3">
<h3 class="anchored" data-anchor-id="a-bonus-chapter-real-time-membership-offers">A Bonus Chapter: Real-Time Membership Offers</h3>
</section>
</section>
<section id="ndefinedprepare" class="level2">
<h2 class="anchored" data-anchor-id="ndefinedprepare">2. ndefinedPrepare</h2>
<section id="data-sources" class="level3">
<h3 class="anchored" data-anchor-id="data-sources">Data Sources</h3>
<p>For this analysis, I will use Cyclistic’s historical trip data to identify trends. To ensure technical efficiency and follow project guidelines, the scope is limited to the following datasets:</p>
<p><strong>1.-</strong> <strong>Divvy_Trips_2019_Q1.csv</strong><br>
<strong>2.-</strong> <strong>Divvy_Trips_2020_Q1.csv</strong></p>
<p>This data is public and has been made available by Motivate International Inc.&nbsp;under this <a href="https://divvybikes.com/data-license-agreement">license</a>.</p>
</section>
<section id="data-credibility-roccc-analysis" class="level3">
<h3 class="anchored" data-anchor-id="data-credibility-roccc-analysis">Data Credibility (ROCCC Analysis)</h3>
<ul>
<li><strong>Reliable:</strong> The data is accurate and complete, representing a full quarter of activity for each year.</li>
<li><strong>Original:</strong> The data comes directly from the City of Chicago’s bike-share program (Divvy).</li>
<li><strong>Comprehensive:</strong> It includes essential variables such as ride duration, start/end times, and station names.</li>
<li><strong>Current:</strong> While from 2019-2020, it provides the necessary historical context to answer the primary business question.</li>
<li><strong>Cited:</strong> The data is officially documented and maintained by the service provider.</li>
</ul>
</section>
<section id="data-integrity-privacy" class="level3">
<h3 class="anchored" data-anchor-id="data-integrity-privacy">Data Integrity &amp; Privacy</h3>
<ul>
<li><strong>Privacy:</strong> To protect user identity, personally identifiable information (PII) such as credit card numbers and home addresses has been excluded from the datasets.</li>
<li><strong>Limitations:</strong> Demographic data (gender and age) is available for 2019 but was removed from the 2020 dataset; therefore, this analysis will focus primarily on usage patterns rather than demographics.</li>
</ul>
</section>
</section>
<section id="process" class="level2">
<h2 class="anchored" data-anchor-id="process">3. Process</h2>
<p>In this phase, the data is processed to ensure it is clean, consistent, and ready for analysis. I am using <strong>R</strong> and the <strong>tidyverse</strong> ecosystem due to their efficiency in handling large datasets and ensuring reproducible results.</p>
<section id="setup-and-data-import" class="level3">
<h3 class="anchored" data-anchor-id="setup-and-data-import">3.1 Setup and Data Import</h3>
<p>First, I load the necessary libraries and import the datasets for the first quarter of 2019 and 2020. Following the project guidelines, the scope is focused on these specific periods to ensure technical efficiency.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Import libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidytext)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidytext' was built under R version 4.5.2</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import datasets</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>q1_2019 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Divvy_Trips_2019_Q1.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>q1_2020 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Divvy_Trips_2020_Q1.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="data-inspection" class="level3">
<h3 class="anchored" data-anchor-id="data-inspection">3.2 Data Inspection</h3>
<p>Before any manipulation, it is essential to understand the structure and data types of the imported datasets. This step confirms the consistency of the data and identifies necessary cleaning tasks.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect the structure of both datasets</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(q1_2019)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 365,069
Columns: 12
$ trip_id           &lt;dbl&gt; 21742443, 21742444, 21742445, 21742446, 21742447, 21…
$ start_time        &lt;dttm&gt; 2019-01-01 00:04:37, 2019-01-01 00:08:13, 2019-01-0…
$ end_time          &lt;dttm&gt; 2019-01-01 00:11:07, 2019-01-01 00:15:34, 2019-01-0…
$ bikeid            &lt;dbl&gt; 2167, 4386, 1524, 252, 1170, 2437, 2708, 2796, 6205,…
$ tripduration      &lt;dbl&gt; 390, 441, 829, 1783, 364, 216, 177, 100, 1727, 336, …
$ from_station_id   &lt;dbl&gt; 199, 44, 15, 123, 173, 98, 98, 211, 150, 268, 299, 2…
$ from_station_name &lt;chr&gt; "Wabash Ave &amp; Grand Ave", "State St &amp; Randolph St", …
$ to_station_id     &lt;dbl&gt; 84, 624, 644, 176, 35, 49, 49, 142, 148, 141, 295, 4…
$ to_station_name   &lt;chr&gt; "Milwaukee Ave &amp; Grand Ave", "Dearborn St &amp; Van Bure…
$ usertype          &lt;chr&gt; "Subscriber", "Subscriber", "Subscriber", "Subscribe…
$ gender            &lt;chr&gt; "Male", "Female", "Female", "Male", "Male", "Female"…
$ birthyear         &lt;dbl&gt; 1989, 1990, 1994, 1993, 1994, 1983, 1984, 1990, 1995…</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(q1_2020)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 426,887
Columns: 13
$ ride_id            &lt;chr&gt; "EACB19130B0CDA4A", "8FED874C809DC021", "789F3C21E4…
$ rideable_type      &lt;chr&gt; "docked_bike", "docked_bike", "docked_bike", "docke…
$ started_at         &lt;dttm&gt; 2020-01-21 20:06:59, 2020-01-30 14:22:39, 2020-01-…
$ ended_at           &lt;dttm&gt; 2020-01-21 20:14:30, 2020-01-30 14:26:22, 2020-01-…
$ start_station_name &lt;chr&gt; "Western Ave &amp; Leland Ave", "Clark St &amp; Montrose Av…
$ start_station_id   &lt;dbl&gt; 239, 234, 296, 51, 66, 212, 96, 96, 212, 38, 117, 1…
$ end_station_name   &lt;chr&gt; "Clark St &amp; Leland Ave", "Southport Ave &amp; Irving Pa…
$ end_station_id     &lt;dbl&gt; 326, 318, 117, 24, 212, 96, 212, 212, 96, 100, 632,…
$ start_lat          &lt;dbl&gt; 41.9665, 41.9616, 41.9401, 41.8846, 41.8856, 41.889…
$ start_lng          &lt;dbl&gt; -87.6884, -87.6660, -87.6455, -87.6319, -87.6418, -…
$ end_lat            &lt;dbl&gt; 41.9671, 41.9542, 41.9402, 41.8918, 41.8899, 41.884…
$ end_lng            &lt;dbl&gt; -87.6674, -87.6644, -87.6530, -87.6206, -87.6343, -…
$ member_casual      &lt;chr&gt; "member", "member", "member", "member", "member", "…</code></pre>
</div>
</div>
</section>
<section id="column-standardization" class="level3">
<h3 class="anchored" data-anchor-id="column-standardization">3.3 Column Standardization</h3>
<p>The inspection confirmed that the 2019 dataset uses a legacy naming convention (e.g., <code>trip_id</code>, <code>usertype</code>) compared to the 2020 version. To facilitate a clean merge, I am renaming the 2019 columns to align with the current standard.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>q1_2019 <span class="ot">&lt;-</span> q1_2019 <span class="sc">|&gt;</span>  </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">ride_id =</span> trip_id,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">rideable_type =</span> bikeid,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">started_at =</span> start_time,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">ended_at =</span> end_time,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">start_station_name =</span> from_station_name,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">start_station_id =</span> from_station_id,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">end_station_name =</span> to_station_name,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">end_station_id =</span> to_station_id,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">member_casual =</span> usertype)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="data-consistency-type-conversion" class="level3">
<h3 class="anchored" data-anchor-id="data-consistency-type-conversion">3.4 Data Consistency &amp; Type Conversion</h3>
<p>After renaming the columns, it is crucial to align the data types. In the 2019 dataset, <code>ride_id</code> and <code>rideable_type</code> are stored as numeric values, whereas the 2020 dataset stores them as characters. I will convert the 2019 columns to character format to ensure a seamless merge.</p>
<p>Additionally, I am consolidating the <code>member_casual</code> labels. The 2019 data uses “Subscriber” and “Customer,” while 2020 uses “member” and “casual.” I will standardize these to the current two-category format.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert IDs to character for compatibility</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>q1_2019 <span class="ot">&lt;-</span> q1_2019 <span class="sc">|&gt;</span>  </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ride_id =</span> <span class="fu">as.character</span>(ride_id),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">rideable_type =</span> <span class="fu">as.character</span>(rideable_type)) </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Consolidate user labels in both datasets</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>q1_2019 <span class="ot">&lt;-</span> q1_2019 <span class="sc">|&gt;</span> </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">member_casual =</span> <span class="fu">recode</span>(member_casual,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Subscriber"</span> <span class="ot">=</span> <span class="st">"member"</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Customer"</span> <span class="ot">=</span> <span class="st">"casual"</span>))</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>q1_2020 <span class="ot">&lt;-</span> q1_2020 <span class="sc">|&gt;</span> </span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">member_casual =</span> <span class="fu">recode</span>(member_casual,</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Subscriber"</span> <span class="ot">=</span> <span class="st">"member"</span>,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Customer"</span> <span class="ot">=</span> <span class="st">"casual"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="merging-datasets" class="level3">
<h3 class="anchored" data-anchor-id="merging-datasets">3.5 Merging Datasets</h3>
<p>With identical column names and data types, I am stacking the datasets into a single data frame named <code>all_trips</code>. To optimize system memory, I will remove the original data frames from the environment once the merge is complete.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Stack the data frames</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>all_trips <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(q1_2019, q1_2020)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove separate data frames to save RAM</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(q1_2019, q1_2020)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="adding-time-metrics" class="level3">
<h3 class="anchored" data-anchor-id="adding-time-metrics">3.6 Adding Time Metrics</h3>
<p>To answer how users utilize the service differently, I will extract the date, month, and day of the week from the <code>started_at</code> column. Additionally, I will calculate the <code>ride_length</code> in minutes.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure date labels are set to English for consistency</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.setlocale</span>(<span class="st">"LC_TIME"</span>, <span class="st">"English"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "English_United States.1252"</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract date components and calculate duration</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>all_trips <span class="ot">&lt;-</span> all_trips <span class="sc">|&gt;</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as.Date</span>(started_at),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">month =</span> <span class="fu">format</span>(<span class="fu">as.Date</span>(date), <span class="st">"%m"</span>),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">day =</span> <span class="fu">format</span>(<span class="fu">as.Date</span>(date), <span class="st">"%d"</span>),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">year =</span> <span class="fu">format</span>(<span class="fu">as.Date</span>(date), <span class="st">"%Y"</span>),</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">day_of_week =</span> <span class="fu">format</span>(<span class="fu">as.Date</span>(date), <span class="st">"%A"</span>),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">ride_length =</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(ended_at, started_at, <span class="at">units =</span> <span class="st">"mins"</span>)))</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Quick check of the new columns</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(all_trips <span class="sc">|&gt;</span> <span class="fu">select</span>(started_at, ended_at, ride_length, day_of_week))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  started_at          ended_at            ride_length day_of_week
  &lt;dttm&gt;              &lt;dttm&gt;                    &lt;dbl&gt; &lt;chr&gt;      
1 2019-01-01 00:04:37 2019-01-01 00:11:07        6.5  Tuesday    
2 2019-01-01 00:08:13 2019-01-01 00:15:34        7.35 Tuesday    
3 2019-01-01 00:13:23 2019-01-01 00:27:12       13.8  Tuesday    
4 2019-01-01 00:13:45 2019-01-01 00:43:28       29.7  Tuesday    
5 2019-01-01 00:14:52 2019-01-01 00:20:56        6.07 Tuesday    
6 2019-01-01 00:15:33 2019-01-01 00:19:09        3.6  Tuesday    </code></pre>
</div>
</div>
</section>
<section id="data-cleaning-and-validation" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning-and-validation">3.7 Data Cleaning and Validation</h3>
<p>The final step in the process phase is to remove data that could skew the results. This includes trips with a duration of zero or less, and entries associated with administrative stations (such as “HQ QR”) that do not represent actual customer trips.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter out invalid durations and administrative station entries</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>all_trips <span class="ot">&lt;-</span> all_trips <span class="sc">|&gt;</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(start_station_name <span class="sc">!=</span> <span class="st">"HQ QR"</span> <span class="sc">|</span> <span class="fu">is.na</span>(start_station_name)) <span class="sc">|&gt;</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ride_length <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># station_names validation</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>all_trips <span class="sc">|&gt;</span> </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(start_station_id) <span class="sc">|&gt;</span> </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">n_distinct</span>(start_station_name) <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">names =</span> <span class="fu">list</span>(<span class="fu">unique</span>(start_station_name))) <span class="sc">|&gt;</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(<span class="at">cols =</span> names)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 48 × 2
   start_station_id names                               
              &lt;dbl&gt; &lt;chr&gt;                               
 1                2 Buckingham Fountain (Temp)          
 2                2 Buckingham Fountain                 
 3               19 Loomis St &amp; Taylor St (*)           
 4               19 Throop (Loomis) St &amp; Taylor St      
 5               23 Orleans St &amp; Elm St (*)             
 6               23 Orleans St &amp; Elm St                 
 7               89 Financial Pl &amp; Ida B Wells Dr (Temp)
 8               89 Financial Pl &amp; Ida B Wells Dr       
 9              103 Clinton St &amp; Polk St (*)            
10              103 Clinton St &amp; Polk St                
# ℹ 38 more rows</code></pre>
</div>
</div>
</section>
<section id="station-name-standardization" class="level3">
<h3 class="anchored" data-anchor-id="station-name-standardization">3.8 Station Name Standardization</h3>
<p>A preliminary group analysis revealed that the same physical docking station was appearing under multiple names due to administrative tags or minor naming updates (e.g., ID 208 recorded as both ‘Ashland Ave’ and ‘Laflin St’). <strong>Failing to consolidate these would lead to fragmented insights</strong>, underreporting the popularity of key locations. I have programmatically unified these identities to ensure a single source of truth for location-based behavior.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Remove temporary and special character tags</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="ot">&lt;-</span> all_trips <span class="sc">|&gt;</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(start_station_name, end_station_name), </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                <span class="sc">~</span> <span class="fu">str_remove_all</span>(., <span class="st">" </span><span class="sc">\\</span><span class="st">(Temp</span><span class="sc">\\</span><span class="st">)| </span><span class="sc">\\</span><span class="st">(</span><span class="sc">\\</span><span class="st">*</span><span class="sc">\\</span><span class="st">)"</span>)))</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Consolidate specific ID-name mismatches based on geographic verification</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="ot">&lt;-</span> all_trips_v2 <span class="sc">|&gt;</span> </span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">start_station_name =</span> <span class="fu">case_when</span>(</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    start_station_id <span class="sc">==</span> <span class="dv">19</span>  <span class="sc">~</span> <span class="st">"Loomis St &amp; Taylor St"</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    start_station_id <span class="sc">==</span> <span class="dv">208</span> <span class="sc">~</span> <span class="st">"Ashland Ave &amp; 21st St"</span>,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    start_station_id <span class="sc">==</span> <span class="dv">217</span> <span class="sc">~</span> <span class="st">"Racine Ave &amp; Fulton St"</span>,</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    start_station_id <span class="sc">==</span> <span class="dv">286</span> <span class="sc">~</span> <span class="st">"Franklin St &amp; Quincy St"</span>,</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> start_station_name</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">end_station_name =</span> <span class="fu">case_when</span>(</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>    end_station_id <span class="sc">==</span> <span class="dv">19</span>  <span class="sc">~</span> <span class="st">"Loomis St &amp; Taylor St"</span>,</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    end_station_id <span class="sc">==</span> <span class="dv">208</span> <span class="sc">~</span> <span class="st">"Ashland Ave &amp; 21st St"</span>,</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>    end_station_id <span class="sc">==</span> <span class="dv">217</span> <span class="sc">~</span> <span class="st">"Racine Ave &amp; Fulton St"</span>,</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>    end_station_id <span class="sc">==</span> <span class="dv">286</span> <span class="sc">~</span> <span class="st">"Franklin St &amp; Quincy St"</span>,</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> end_station_name</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Final Verification: Checking if any station still has more than one name</span></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="sc">|&gt;</span> </span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(start_station_id) <span class="sc">|&gt;</span> </span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">unique_names =</span> <span class="fu">n_distinct</span>(start_station_name)) <span class="sc">|&gt;</span> </span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(unique_names <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 2
# ℹ 2 variables: start_station_id &lt;dbl&gt;, unique_names &lt;int&gt;</code></pre>
</div>
</div>
</section>
<section id="coordinate-enrichment-backfilling" class="level3">
<h3 class="anchored" data-anchor-id="coordinate-enrichment-backfilling">3.9 Coordinate Enrichment (Backfilling)</h3>
<p>Since the 2019 dataset lacks geographic coordinates, I will use the <code>station_id</code> to map the latitude and longitude from the 2020 records to the 2019 ones. This ensures a consistent geographic analysis across the entire timeframe.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: coordinate-mapping-full</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Create a reference table for all unique station coordinates</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>station_map <span class="ot">&lt;-</span> all_trips_v2 <span class="sc">|&gt;</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(start_lat)) <span class="sc">|&gt;</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(start_station_id) <span class="sc">|&gt;</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">ref_lat =</span> <span class="fu">mean</span>(start_lat, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">ref_lng =</span> <span class="fu">mean</span>(start_lng, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">'drop'</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Enrich both Start and End coordinates in a single flow</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="ot">&lt;-</span> all_trips_v2 <span class="sc">|&gt;</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Enrich Start Stations</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(station_map, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"start_station_id"</span> <span class="ot">=</span> <span class="st">"start_station_id"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">start_lat =</span> <span class="fu">coalesce</span>(start_lat, ref_lat),</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">start_lng =</span> <span class="fu">coalesce</span>(start_lng, ref_lng)</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(ref_lat, ref_lng)) <span class="sc">|&gt;</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Enrich End Stations</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(station_map, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"end_station_id"</span> <span class="ot">=</span> <span class="st">"start_station_id"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">end_lat =</span> <span class="fu">coalesce</span>(end_lat, ref_lat),</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">end_lng =</span> <span class="fu">coalesce</span>(end_lng, ref_lng)</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(ref_lat, ref_lng))</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the intermediate dataset to free up memory for analysis</span></span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(station_map)</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Final Data Quality Verification</span></span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a>summary_geo <span class="ot">&lt;-</span> all_trips_v2 <span class="sc">|&gt;</span> </span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing_start =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(start_lat)),</span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing_end =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(end_lat))</span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(summary_geo)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  missing_start missing_end
          &lt;int&gt;       &lt;int&gt;
1            40          56</code></pre>
</div>
</div>
<p>By applying this to both start and end stations, I successfully reduced the missing geographic data from 46% to less than <strong>0.01%</strong> of the total records.</p>
</section>
<section id="final-data-type-transformation" class="level3">
<h3 class="anchored" data-anchor-id="final-data-type-transformation">3.10 Final Data Type Transformation</h3>
<p>To ensure analytical accuracy, I am converting categorical variables—such as station IDs, months, and days—into factors. This step is crucial for maintaining the correct chronological order in visualizations and ensuring that identification numbers are not treated as mathematical values.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set locale to English again just to be safe before factoring</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.setlocale</span>(<span class="st">"LC_TIME"</span>, <span class="st">"English"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "English_United States.1252"</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="ot">&lt;-</span> all_trips_v2 <span class="sc">|&gt;</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># IDs as characters (since they are identifications, not numbers)</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">start_station_id =</span> <span class="fu">as.character</span>(start_station_id),</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">end_station_id =</span> <span class="fu">as.character</span>(end_station_id),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Temporal variables as ordered factors</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">month =</span> <span class="fu">factor</span>(month, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"01"</span>, <span class="st">"02"</span>, <span class="st">"03"</span>), <span class="at">ordered =</span> <span class="cn">TRUE</span>),</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">day_of_week =</span> <span class="fu">factor</span>(day_of_week, </span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>                         <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Monday"</span>, <span class="st">"Tuesday"</span>, <span class="st">"Wednesday"</span>, <span class="st">"Thursday"</span>, </span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Friday"</span>, <span class="st">"Saturday"</span>, <span class="st">"Sunday"</span>), </span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>                         <span class="at">ordered =</span> <span class="cn">TRUE</span>),</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Year and User Type as factors</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="fu">factor</span>(year),</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">member_casual =</span> <span class="fu">factor</span>(member_casual)</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="final-column-selection" class="level3">
<h3 class="anchored" data-anchor-id="final-column-selection">3.11 Final Column Selection</h3>
<p>To ensure a consistent analysis between 2019 and 2020, I have opted to remove the <code>gender</code> and <code>birthyear</code> columns. These variables were not collected in the 2020 dataset, and including them would result in an incomplete demographic profile. Additionally, the <code>tripduration</code> column from 2019 was removed in favor of the newly calculated <code>ride_length</code> variable to ensure a uniform measurement unit (minutes) across all records.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove inconsistent or redundant columns</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="ot">&lt;-</span> all_trips_v2 <span class="sc">|&gt;</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(gender, birthyear, tripduration))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="data-health-check-quality-assurance" class="level3">
<h3 class="anchored" data-anchor-id="data-health-check-quality-assurance">3.12 Data Health Check &amp; Quality Assurance</h3>
<p>As a final step before analysis, I conducted a quality check using the <code>skimr</code> library to ensure there are no missing values in critical columns and to examine the distribution of <code>ride_length</code>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the clean dataset</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(all_trips_v2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">all_trips_v2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">788189</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">19</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Date</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">POSIXct</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 24%">
<col style="width: 12%">
<col style="width: 18%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ride_id</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">788189</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">rideable_type</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4770</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">start_station_id</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">611</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">start_station_name</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">611</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">end_station_id</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">612</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">end_station_name</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">612</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">day</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: Date</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">min</th>
<th style="text-align: left;">max</th>
<th style="text-align: left;">median</th>
<th style="text-align: right;">n_unique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">date</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">2019-01-01</td>
<td style="text-align: left;">2020-03-31</td>
<td style="text-align: left;">2020-01-07</td>
<td style="text-align: right;">181</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">ordered</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: left;">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">member_casual</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">mem: 720312, cas: 67877</td>
</tr>
<tr class="even">
<td style="text-align: left;">month</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">03: 305819, 01: 247156, 02: 235214</td>
</tr>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">202: 423120, 201: 365069</td>
</tr>
<tr class="even">
<td style="text-align: left;">day_of_week</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Tue: 135285, Thu: 132375, Wed: 129592, Fri: 123181</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">start_lat</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">41.90</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">41.74</td>
<td style="text-align: right;">41.88</td>
<td style="text-align: right;">41.89</td>
<td style="text-align: right;">41.91</td>
<td style="text-align: right;">42.06</td>
<td style="text-align: left;">▁▁▇▂▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">start_lng</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-87.64</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">-87.77</td>
<td style="text-align: right;">-87.65</td>
<td style="text-align: right;">-87.64</td>
<td style="text-align: right;">-87.63</td>
<td style="text-align: right;">-87.55</td>
<td style="text-align: left;">▁▁▇▇▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">end_lat</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">41.90</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">41.74</td>
<td style="text-align: right;">41.88</td>
<td style="text-align: right;">41.89</td>
<td style="text-align: right;">41.92</td>
<td style="text-align: right;">42.06</td>
<td style="text-align: left;">▁▁▇▂▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">end_lng</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-87.64</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">-87.77</td>
<td style="text-align: right;">-87.65</td>
<td style="text-align: right;">-87.64</td>
<td style="text-align: right;">-87.63</td>
<td style="text-align: right;">-87.55</td>
<td style="text-align: left;">▁▁▇▇▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ride_length</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">19.82</td>
<td style="text-align: right;">554.87</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">5.52</td>
<td style="text-align: right;">8.98</td>
<td style="text-align: right;">15.20</td>
<td style="text-align: right;">177200.37</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: POSIXct</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">min</th>
<th style="text-align: left;">max</th>
<th style="text-align: left;">median</th>
<th style="text-align: right;">n_unique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">started_at</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">2019-01-01 00:04:37</td>
<td style="text-align: left;">2020-03-31 23:51:34</td>
<td style="text-align: left;">2020-01-07 07:59:53</td>
<td style="text-align: right;">738828</td>
</tr>
<tr class="even">
<td style="text-align: left;">ended_at</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">2019-01-01 00:11:07</td>
<td style="text-align: left;">2020-05-19 20:10:34</td>
<td style="text-align: left;">2020-01-07 08:10:57</td>
<td style="text-align: right;">734450</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Analyst Note:</strong> The <code>skim</code> output confirms a clean dataset with <strong>788,189 observations</strong>. While coordinates (<code>lat</code>/<code>lng</code>) show some missing values (46%), this does not impact the primary business question regarding usage patterns by membership type.</p>
</blockquote>
<p><strong>Critical Data Note:</strong> The <code>skim</code> analysis reveals significant outliers in <code>ride_length</code>. While the median trip is only <strong>8.98 minutes</strong>, the maximum value reaches an unrealistic <strong>177,200.37 minutes</strong> (approx. 123 days). These outliers skew the distribution, as seen in the “flat” histogram. For the subsequent analysis, I will consider these anomalies to ensure the average metrics represent true user behavior.</p>
</section>
<section id="outlier-treatment-business-logic-validation" class="level3">
<h3 class="anchored" data-anchor-id="outlier-treatment-business-logic-validation">3.13 Outlier Treatment &amp; Business Logic Validation</h3>
<p>A critical anomaly was detected during the quality check: several trips recorded durations exceeding <strong>100 days</strong>. Based on <strong>industry standards</strong> for urban bike-sharing systems and Cyclistic’s business model—focused on short-term city transit—trips lasting more than <strong>24 hours (1,440 minutes)</strong> are considered technical errors, thefts, or system failures rather than intentional rentals.</p>
<p>To ensure that descriptive statistics (like the average) reflect true user behavior, I have capped the dataset at 24 hours.</p>
<blockquote class="blockquote">
<p><strong>Note for the Operations Team:</strong> This 24-hour threshold is a data-driven recommendation. I suggest the Cyclistic technical team validates these specific records to confirm if they represent unreturned bikes or docking station malfunctions.</p>
</blockquote>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering trips to a maximum of 24 hours (1,440 minutes)</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="ot">&lt;-</span> all_trips_v2 <span class="sc">|&gt;</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ride_length <span class="sc">&lt;=</span> <span class="dv">1440</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the intermediate dataset to free up memory for analysis</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(all_trips)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Verify the final dimensions of the clean dataset</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Final dimensions of the clean dataset:"</span>, <span class="fu">paste</span>(<span class="fu">dim</span>(all_trips_v2), <span class="at">collapse =</span> <span class="st">" x "</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Final dimensions of the clean dataset: 787707 x 19"</code></pre>
</div>
</div>
</section>
</section>
<section id="analyze" class="level2">
<h2 class="anchored" data-anchor-id="analyze">4. Analyze</h2>
<p>With a clean and consolidated dataset of <strong>787,707 records</strong>, I will now perform a descriptive analysis to uncover trends and patterns. The focus is on identifying how usage differs between members and casual riders.</p>
<section id="general-descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="general-descriptive-statistics">4.1 General Descriptive Statistics</h3>
<p>First, I will establish a baseline for the <code>ride_length</code> variable. As noted in the previous phase, the distribution is skewed, so comparing the mean and median is essential.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics for ride_length (in minutes)</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="sc">|&gt;</span> </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">number_of_rides =</span> <span class="fu">n</span>(),</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_ride_length =</span> <span class="fu">mean</span>(ride_length),</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_ride_length =</span> <span class="fu">median</span>(ride_length),</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_ride_length =</span> <span class="fu">max</span>(ride_length),</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_ride_length =</span> <span class="fu">min</span>(ride_length)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Number of rides"</span>, <span class="st">"Mean"</span>, <span class="st">"Median"</span>, <span class="st">"Max"</span>, <span class="st">"Min"</span>),</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">align =</span> <span class="st">"ccccc"</span>,</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Table 1. Ride Duration Summary Statistics"</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 1. Ride Duration Summary Statistics</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Number of rides</th>
<th style="text-align: center;">Mean</th>
<th style="text-align: center;">Median</th>
<th style="text-align: center;">Max</th>
<th style="text-align: center;">Min</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">787707</td>
<td style="text-align: center;">13.72</td>
<td style="text-align: center;">8.98</td>
<td style="text-align: center;">1435.92</td>
<td style="text-align: center;">0.02</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The baseline analysis of <code>ride_length</code> reveals that the average trip duration is <strong>13.72 minutes</strong>, while the median is <strong>8.98 minutes</strong>. The significant gap between the mean and median confirms that, even after removing extreme outliers (trips &gt; 24 hours), the distribution remains skewed by longer occasional rides.</p>
</section>
<section id="segmented-analysis-members-vs.-casuals" class="level3">
<h3 class="anchored" data-anchor-id="segmented-analysis-members-vs.-casuals">4.2 Segmented Analysis: Members vs.&nbsp;Casuals</h3>
<p>The core of our task is the comparison between user types. Initial data shows a clear dominance of members in total volume (720,125 members vs.&nbsp;67,582 casuals). Now, let’s see how their trip durations compare.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparing mean and median duration by user type</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="sc">|&gt;</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(member_casual) <span class="sc">|&gt;</span> </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">number_of_rides =</span> <span class="fu">n</span>(),</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_ride_length =</span> <span class="fu">mean</span>(ride_length),</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_ride_length =</span> <span class="fu">median</span>(ride_length),</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_ride_length =</span> <span class="fu">max</span>(ride_length),</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_ride_length =</span> <span class="fu">min</span>(ride_length)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"User Type"</span>, <span class="st">"Number of rides"</span>, <span class="st">"Mean"</span>, <span class="st">"Median"</span>, <span class="st">"Max"</span>, <span class="st">"Min"</span>),</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">align =</span> <span class="st">"cccccc"</span>,</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Table 2. Mean and Median Ride Duration by User Type"</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 2. Mean and Median Ride Duration by User Type</caption>
<thead>
<tr class="header">
<th style="text-align: center;">User Type</th>
<th style="text-align: center;">Number of rides</th>
<th style="text-align: center;">Mean</th>
<th style="text-align: center;">Median</th>
<th style="text-align: center;">Max</th>
<th style="text-align: center;">Min</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">casual</td>
<td style="text-align: center;">67582</td>
<td style="text-align: center;">38.38</td>
<td style="text-align: center;">23.13</td>
<td style="text-align: center;">1435.92</td>
<td style="text-align: center;">0.03</td>
</tr>
<tr class="even">
<td style="text-align: center;">member</td>
<td style="text-align: center;">720125</td>
<td style="text-align: center;">11.41</td>
<td style="text-align: center;">8.47</td>
<td style="text-align: center;">1433.07</td>
<td style="text-align: center;">0.02</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>When segmenting by user type, we find a stark contrast in behavior. While annual members account for the vast majority of trips (<strong>720,125 rides</strong>), casual riders utilize the equipment for significantly longer periods.</p>
<p><strong>Key Business Insight:</strong> Casual riders’ median trip duration (<strong>23.13 min</strong>) is nearly <strong>three times longer</strong> than that of members (<strong>8.47 min</strong>). This data <strong>provides statistical evidence to support the Marketing Team’s observation</strong> that Members use Cyclistic as a highly efficient “A-to-B” commuting tool, while Casuals view the service as a platform for leisure or sightseeing.</p>
</section>
<section id="weekly-usage-patterns" class="level3">
<h3 class="anchored" data-anchor-id="weekly-usage-patterns">4.3 Weekly Usage Patterns</h3>
<p>To understand when these users are most active, I analyzed the number of rides and average duration for each day of the week. This analysis is crucial for identifying routine-based versus leisure-based behaviors.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of rides and average duration by day of week</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="sc">|&gt;</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(member_casual, day_of_week) <span class="sc">|&gt;</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">number_of_rides =</span> <span class="fu">n</span>(),</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">average_ride_length =</span> <span class="fu">mean</span>(ride_length),</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">'drop'</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"User Type"</span>, <span class="st">"Day of Week"</span>, <span class="st">"Number of Rides"</span>, <span class="st">"Avg Duration (min)"</span>),</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">align =</span> <span class="st">"llcc"</span>,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Table 3. Weekly Usage Patterns: Volume and Duration"</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 3. Weekly Usage Patterns: Volume and Duration</caption>
<thead>
<tr class="header">
<th style="text-align: left;">User Type</th>
<th style="text-align: left;">Day of Week</th>
<th style="text-align: center;">Number of Rides</th>
<th style="text-align: center;">Avg Duration (min)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">casual</td>
<td style="text-align: left;">Monday</td>
<td style="text-align: center;">5569</td>
<td style="text-align: center;">34.43</td>
</tr>
<tr class="even">
<td style="text-align: left;">casual</td>
<td style="text-align: left;">Tuesday</td>
<td style="text-align: center;">7288</td>
<td style="text-align: center;">35.56</td>
</tr>
<tr class="odd">
<td style="text-align: left;">casual</td>
<td style="text-align: left;">Wednesday</td>
<td style="text-align: center;">7655</td>
<td style="text-align: center;">41.12</td>
</tr>
<tr class="even">
<td style="text-align: left;">casual</td>
<td style="text-align: left;">Thursday</td>
<td style="text-align: center;">7105</td>
<td style="text-align: center;">35.27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">casual</td>
<td style="text-align: left;">Friday</td>
<td style="text-align: center;">7971</td>
<td style="text-align: center;">37.12</td>
</tr>
<tr class="even">
<td style="text-align: left;">casual</td>
<td style="text-align: left;">Saturday</td>
<td style="text-align: center;">13416</td>
<td style="text-align: center;">38.95</td>
</tr>
<tr class="odd">
<td style="text-align: left;">casual</td>
<td style="text-align: left;">Sunday</td>
<td style="text-align: center;">18578</td>
<td style="text-align: center;">40.86</td>
</tr>
<tr class="even">
<td style="text-align: left;">member</td>
<td style="text-align: left;">Monday</td>
<td style="text-align: center;">110412</td>
<td style="text-align: center;">11.10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">member</td>
<td style="text-align: left;">Tuesday</td>
<td style="text-align: center;">127946</td>
<td style="text-align: center;">11.32</td>
</tr>
<tr class="even">
<td style="text-align: left;">member</td>
<td style="text-align: left;">Wednesday</td>
<td style="text-align: center;">121878</td>
<td style="text-align: center;">11.17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">member</td>
<td style="text-align: left;">Thursday</td>
<td style="text-align: center;">125198</td>
<td style="text-align: center;">11.07</td>
</tr>
<tr class="even">
<td style="text-align: left;">member</td>
<td style="text-align: left;">Friday</td>
<td style="text-align: center;">115132</td>
<td style="text-align: center;">11.10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">member</td>
<td style="text-align: left;">Saturday</td>
<td style="text-align: center;">59381</td>
<td style="text-align: center;">12.44</td>
</tr>
<tr class="even">
<td style="text-align: left;">member</td>
<td style="text-align: left;">Sunday</td>
<td style="text-align: center;">60178</td>
<td style="text-align: center;">12.92</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Key Findings:</strong></p>
<ul>
<li><p><strong>Members (The Commuters):</strong> Their highest volume of rides occurs during the workweek (Monday through Friday), with a noticeable decline on Saturdays and Sundays. Their average duration remains remarkably consistent throughout the week, reinforcing the idea of routine, time-sensitive trips.</p></li>
<li><p><strong>Casual Riders (The Leisure Seekers):</strong> While their total volume is lower than that of members, their activity peaks during the weekend. Furthermore, their average ride duration increases significantly on Saturdays and Sundays, suggesting that their use of Cyclistic is primarily tied to recreational or non-routine activities.</p></li>
</ul>
</section>
<section id="hourly-usage-patterns" class="level3">
<h3 class="anchored" data-anchor-id="hourly-usage-patterns">4.4 Hourly Usage Patterns</h3>
<p>To further differentiate user behavior, I analyzed the distribution of rides by the hour of the day. This provides insight into whether the bikes are being used for scheduled activities (like commuting) or flexible ones (like tourism).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the hour from the starting timestamp</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="ot">&lt;-</span> all_trips_v2 <span class="sc">|&gt;</span> </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hour =</span> <span class="fu">hour</span>(started_at))</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize the number of rides per hour and user type</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="sc">|&gt;</span> </span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(member_casual, hour) <span class="sc">|&gt;</span> </span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">number_of_rides =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">'drop'</span>) <span class="sc">|&gt;</span> </span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> member_casual, <span class="at">values_from =</span> number_of_rides) <span class="sc">|&gt;</span> </span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Hour of Day"</span>, <span class="st">"Casual Rides"</span>, <span class="st">"Member Rides"</span>),</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">align =</span> <span class="st">"ccc"</span>,</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Table 4. Hourly Distribution of Rides by User Type"</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 4. Hourly Distribution of Rides by User Type</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Hour of Day</th>
<th style="text-align: center;">Casual Rides</th>
<th style="text-align: center;">Member Rides</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">460</td>
<td style="text-align: center;">2956</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">328</td>
<td style="text-align: center;">1740</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">240</td>
<td style="text-align: center;">1129</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">143</td>
<td style="text-align: center;">896</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">91</td>
<td style="text-align: center;">1984</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;">194</td>
<td style="text-align: center;">9040</td>
</tr>
<tr class="odd">
<td style="text-align: center;">6</td>
<td style="text-align: center;">482</td>
<td style="text-align: center;">27697</td>
</tr>
<tr class="even">
<td style="text-align: center;">7</td>
<td style="text-align: center;">1010</td>
<td style="text-align: center;">58611</td>
</tr>
<tr class="odd">
<td style="text-align: center;">8</td>
<td style="text-align: center;">1828</td>
<td style="text-align: center;">78695</td>
</tr>
<tr class="even">
<td style="text-align: center;">9</td>
<td style="text-align: center;">1862</td>
<td style="text-align: center;">35996</td>
</tr>
<tr class="odd">
<td style="text-align: center;">10</td>
<td style="text-align: center;">2776</td>
<td style="text-align: center;">24268</td>
</tr>
<tr class="even">
<td style="text-align: center;">11</td>
<td style="text-align: center;">4236</td>
<td style="text-align: center;">29284</td>
</tr>
<tr class="odd">
<td style="text-align: center;">12</td>
<td style="text-align: center;">5616</td>
<td style="text-align: center;">33544</td>
</tr>
<tr class="even">
<td style="text-align: center;">13</td>
<td style="text-align: center;">7166</td>
<td style="text-align: center;">33015</td>
</tr>
<tr class="odd">
<td style="text-align: center;">14</td>
<td style="text-align: center;">7689</td>
<td style="text-align: center;">32173</td>
</tr>
<tr class="even">
<td style="text-align: center;">15</td>
<td style="text-align: center;">7783</td>
<td style="text-align: center;">43011</td>
</tr>
<tr class="odd">
<td style="text-align: center;">16</td>
<td style="text-align: center;">7608</td>
<td style="text-align: center;">76338</td>
</tr>
<tr class="even">
<td style="text-align: center;">17</td>
<td style="text-align: center;">6963</td>
<td style="text-align: center;">95842</td>
</tr>
<tr class="odd">
<td style="text-align: center;">18</td>
<td style="text-align: center;">4248</td>
<td style="text-align: center;">55544</td>
</tr>
<tr class="even">
<td style="text-align: center;">19</td>
<td style="text-align: center;">2460</td>
<td style="text-align: center;">32561</td>
</tr>
<tr class="odd">
<td style="text-align: center;">20</td>
<td style="text-align: center;">1529</td>
<td style="text-align: center;">19213</td>
</tr>
<tr class="even">
<td style="text-align: center;">21</td>
<td style="text-align: center;">1294</td>
<td style="text-align: center;">13617</td>
</tr>
<tr class="odd">
<td style="text-align: center;">22</td>
<td style="text-align: center;">932</td>
<td style="text-align: center;">8287</td>
</tr>
<tr class="even">
<td style="text-align: center;">23</td>
<td style="text-align: center;">644</td>
<td style="text-align: center;">4684</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Key Findings:</strong></p>
<ul>
<li><p><strong>Members (The Commuter Spikes):</strong> We expect to see two significant peaks in member usage: one between <strong>7:00 AM and 9:00 AM</strong> and another between <strong>4:00 PM and 6:00 PM</strong>. This “double-hump” pattern is a classic indicator of a workforce using the service for daily transit.</p></li>
<li><p><strong>Casual Riders (The Afternoon Curve):</strong> Unlike members, casual riders typically show a steady increase in usage starting late morning, peaking in the <strong>mid-afternoon (12:00 PM - 3:00 PM)</strong>, and gradually declining. This suggests leisure activities that are not bound by strict office hours.</p></li>
</ul>
</section>
<section id="geographic-analysis-top-starting-stations-by-user-type" class="level3">
<h3 class="anchored" data-anchor-id="geographic-analysis-top-starting-stations-by-user-type">4.5 Geographic Analysis: Top Starting Stations by User Type</h3>
<p>To validate the purpose of the trips, I have segmented the top starting stations by user type. This comparison reveals whether stations are located near commercial hubs (work-oriented) or leisure landmarks (recreation-oriented).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Top 10 Stations for Casual Riders</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>top_10_casual <span class="ot">&lt;-</span> all_trips_v2 <span class="sc">|&gt;</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(member_casual <span class="sc">==</span> <span class="st">"casual"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(start_station_name) <span class="sc">|&gt;</span> </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">number_of_rides =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(number_of_rides)) <span class="sc">|&gt;</span> </span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Top 10 Stations for Members</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>top_10_member <span class="ot">&lt;-</span> all_trips_v2 <span class="sc">|&gt;</span> </span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(member_casual <span class="sc">==</span> <span class="st">"member"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(start_station_name) <span class="sc">|&gt;</span> </span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">number_of_rides =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(number_of_rides)) <span class="sc">|&gt;</span> </span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Display Casual Table</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(top_10_casual, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Station Name (Casual)"</span>, <span class="st">"Rides"</span>), </span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Table 5a. Top 10 Starting Stations - Casual Riders"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 5a. Top 10 Starting Stations - Casual Riders</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Station Name (Casual)</th>
<th style="text-align: right;">Rides</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Streeter Dr &amp; Grand Ave</td>
<td style="text-align: right;">2741</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lake Shore Dr &amp; Monroe St</td>
<td style="text-align: right;">2727</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shedd Aquarium</td>
<td style="text-align: right;">1831</td>
</tr>
<tr class="even">
<td style="text-align: left;">Millennium Park</td>
<td style="text-align: right;">1403</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Michigan Ave &amp; Oak St</td>
<td style="text-align: right;">1017</td>
</tr>
<tr class="even">
<td style="text-align: left;">Michigan Ave &amp; Washington St</td>
<td style="text-align: right;">835</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dusable Harbor</td>
<td style="text-align: right;">829</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adler Planetarium</td>
<td style="text-align: right;">826</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Theater on the Lake</td>
<td style="text-align: right;">794</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lake Shore Dr &amp; North Blvd</td>
<td style="text-align: right;">606</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display Member Table</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(top_10_member, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Station Name (Member)"</span>, <span class="st">"Rides"</span>), </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Table 5b. Top 10 Starting Stations - Annual Members"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 5b. Top 10 Starting Stations - Annual Members</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Station Name (Member)</th>
<th style="text-align: right;">Rides</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Canal St &amp; Adams St</td>
<td style="text-align: right;">13797</td>
</tr>
<tr class="even">
<td style="text-align: left;">Clinton St &amp; Washington Blvd</td>
<td style="text-align: right;">13434</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Clinton St &amp; Madison St</td>
<td style="text-align: right;">12889</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kingsbury St &amp; Kinzie St</td>
<td style="text-align: right;">8718</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Columbus Dr &amp; Randolph St</td>
<td style="text-align: right;">8515</td>
</tr>
<tr class="even">
<td style="text-align: left;">Canal St &amp; Madison St</td>
<td style="text-align: right;">7956</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Franklin St &amp; Monroe St</td>
<td style="text-align: right;">7008</td>
</tr>
<tr class="even">
<td style="text-align: left;">Michigan Ave &amp; Washington St</td>
<td style="text-align: right;">6684</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Larrabee St &amp; Kingsbury St</td>
<td style="text-align: right;">6466</td>
</tr>
<tr class="even">
<td style="text-align: left;">Clinton St &amp; Lake St</td>
<td style="text-align: right;">6437</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Analyst Note:</strong> The geographic data reveals two distinct “worlds” within the same city:</p>
<ul>
<li><p><strong>The Leisure Hub (Casuals):</strong> The top stations for casual riders, led by <strong>Streeter Dr &amp; Grand Ave (2,741 rides)</strong> and <strong>Lake Shore Dr &amp; Monroe St (2,727 rides)</strong>, are located exclusively near lakefront tourist attractions, parks, and museums.</p></li>
<li><p><strong>The Transit Hub (Members):</strong> In contrast, member activity is concentrated at transit-linked stations such as <strong>Canal St &amp; Adams St (13,797 rides)</strong> and <strong>Clinton St &amp; Washington Blvd (13,434 rides)</strong>. These stations are adjacent to major metropolitan train terminals (Union Station and Ogilvie Transportation Center), confirming that members primarily use Cyclistic for the “last mile” of their professional daily commute.</p></li>
</ul>
</blockquote>
</section>
</section>
<section id="share-visualization" class="level2">
<h2 class="anchored" data-anchor-id="share-visualization">5. Share (Visualization)</h2>
<p>In this phase, I transform the processed data into visual insights. These visualizations are designed to highlight the behavioral gap between casual riders and annual members, providing the marketing team with clear evidence for their strategy.</p>
<section id="average-ride-duration-the-leisure-gap" class="level3">
<h3 class="anchored" data-anchor-id="average-ride-duration-the-leisure-gap">5.1 Average Ride Duration (The Leisure Gap)</h3>
<p>To establish the primary difference in usage, I first compare the average <code>ride_length</code>. This “quick insight” highlights a massive gap: casual riders consistently spend more time per trip than members.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Average ride length comparison</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="sc">|&gt;</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(member_casual) <span class="sc">|&gt;</span> </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_duration =</span> <span class="fu">mean</span>(ride_length)) <span class="sc">|&gt;</span> </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> member_casual, <span class="at">y =</span> avg_duration, <span class="at">fill =</span> member_casual)) <span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(avg_duration, <span class="dv">2</span>)), </span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">fontface =</span> <span class="st">"bold"</span>) <span class="sc">+</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">42</span>)) <span class="sc">+</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Ride Duration: Casual vs. Member"</span>,</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Casual riders spend significantly more time per trip"</span>,</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"User Type"</span>, </span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Duration (min)"</span>,</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Data Source: Motivate International Inc."</span>) <span class="sc">+</span></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"casual"</span> <span class="ot">=</span> <span class="st">"#F8766D"</span>, <span class="st">"member"</span> <span class="ot">=</span> <span class="st">"#00BFC4"</span>)) <span class="sc">+</span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">"gray"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/visual-duration-comparison-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 1. Comparison of average trip duration between casual riders and annual members.</figcaption>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Analyst Note:</strong> This is the most significant behavioral indicator. Casual riders utilize bikes for <strong>38.38 minutes</strong> on average, nearly <strong>four times longer</strong> than members. This confirms that for casuals, the ride <em>is</em> the activity, while for members, it is primarily a tool for efficient point-to-point transit.</p>
</blockquote>
</section>
<section id="user-distribution-by-day-proportional-analysis" class="level3">
<h3 class="anchored" data-anchor-id="user-distribution-by-day-proportional-analysis">5.2 User Distribution by Day (Proportional Analysis)</h3>
<p>While members provide the bulk of the volume, a proportional analysis reveals that the <strong>market share of casual riders expands significantly on weekends</strong>. This highlights Saturdays and Sundays as the critical window for conversion efforts.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Proportional usage by day of week</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(day_of_week, member_casual) <span class="sc">|&gt;</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(day_of_week) <span class="sc">|&gt;</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percentage =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">|&gt;</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> day_of_week, <span class="at">y =</span> percentage, <span class="at">fill =</span> member_casual)) <span class="sc">+</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Proportional Distribution of User Types"</span>,</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Casual riders' market share doubles on weekends"</span>,</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Day of Week"</span>, </span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Percentage of Total Rides"</span>, <span class="at">fill =</span> <span class="st">"User Type"</span>,</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Data Source: Motivate International Inc."</span>) <span class="sc">+</span></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"casual"</span> <span class="ot">=</span> <span class="st">"#F8766D"</span>, <span class="st">"member"</span> <span class="ot">=</span> <span class="st">"#00BFC4"</span>)) <span class="sc">+</span></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">"gray"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/visual-proportional-day-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 2. Daily proportional distribution showing the increase in casual rider market share during weekends.</figcaption>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Analyst Note:</strong> While members provide the volume baseline during the workweek, the <strong>proportional market share of casual riders nearly doubles on weekends</strong>. This identifies Saturdays and Sundays as the “Golden Window” for conversion-focused marketing campaigns.</p>
</blockquote>
</section>
<section id="hourly-distribution-per-day-the-commuter-pulse" class="level3">
<h3 class="anchored" data-anchor-id="hourly-distribution-per-day-the-commuter-pulse">5.3 Hourly Distribution per Day (The Commuter Pulse)</h3>
<p>By using independent scales, we uncover distinct temporal patterns: commuter spikes for members and an afternoon climb for casuals.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizing number of rides by user type during the day, faceted by day of week</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="sc">|&gt;</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(member_casual, day_of_week, hour) <span class="sc">|&gt;</span> </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">number_of_rides =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">'drop'</span>) <span class="sc">|&gt;</span> </span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> hour, <span class="at">y =</span> number_of_rides, <span class="at">fill =</span> member_casual)) <span class="sc">+</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(member_casual <span class="sc">~</span> day_of_week, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>comma) <span class="sc">+</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Hourly Ride Distribution by User Type"</span>,</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Side-by-side comparison highlights distinct commuter vs. leisure patterns"</span>,</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Hour of Day (24h)"</span>, </span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of Rides"</span>, </span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"User Type"</span>,</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Data Source: Motivate International Inc."</span></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>       ) <span class="sc">+</span></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"casual"</span> <span class="ot">=</span> <span class="st">"#F8766D"</span>, <span class="st">"member"</span> <span class="ot">=</span> <span class="st">"#00BFC4"</span>)) <span class="sc">+</span></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">"gray"</span>),</span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/visual-hourly-distribution-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 3. Hourly ride distribution by day of the week, highlighting commuter spikes vs.&nbsp;leisure curves.</figcaption>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Analyst Note:</strong> Members exhibit sharp spikes at <strong>8:00 AM and 5:00 PM</strong> on weekdays. Casual ridership, however,follows a <strong>steady afternoon climb</strong>, peaking between <strong>1:00 PM and 4:00 PM</strong>. They are <em>afternoon users</em> who could be targeted with off-peak membership.</p>
</blockquote>
</section>
<section id="geographic-distribution-mapping-the-two-worlds" class="level3">
<h3 class="anchored" data-anchor-id="geographic-distribution-mapping-the-two-worlds">5.4 Geographic Distribution (Mapping the Two Worlds)</h3>
<p>The top 10 starting stations by User type reveal a clear “Tourist vs.&nbsp;Worker” split.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Top 10 stations for Casuals vs Members with independent ordering</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  top_10_casual <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">user_type =</span> <span class="st">"Casual"</span>),</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  top_10_member <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">user_type =</span> <span class="st">"Member"</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">station_name =</span> <span class="fu">reorder_within</span>(start_station_name, </span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>                                       number_of_rides, user_type)) <span class="sc">|&gt;</span> </span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> station_name, <span class="at">y =</span> number_of_rides, <span class="at">fill =</span> user_type)) <span class="sc">+</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>user_type, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_reordered</span>() <span class="sc">+</span> </span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Top 10 Starting Stations by User Type"</span>,</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Leisure landmarks for casuals vs. transit hubs for members"</span>,</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Station Name"</span>, </span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of Rides"</span>,</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Data Source: Motivate International Inc."</span></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>       ) <span class="sc">+</span></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Casual"</span> <span class="ot">=</span> <span class="st">"#F8766D"</span>, <span class="st">"Member"</span> <span class="ot">=</span> <span class="st">"#00BFC4"</span>)) <span class="sc">+</span></span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">"gray"</span>),</span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/visual-top-stations-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 4. Top 10 starting stations for both user types, revealing distinct geographic preferences.</figcaption>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Analyst Note:</strong> Casual riders dominate lakefront landmarks like <strong>Streeter Dr &amp; Grand Ave</strong>. Meanwhile, members are concentrated in transit hubs near train terminals, such as <strong>Canal St &amp; Adams St</strong>, which records over <strong>13,000 rides</strong>.</p>
</blockquote>
</section>
<section id="geographic-cluster-map-the-spatial-divide" class="level3">
<h3 class="anchored" data-anchor-id="geographic-cluster-map-the-spatial-divide">5.5 Geographic Cluster Map (The Spatial Divide)</h3>
<p>By plotting the enriched coordinates, we can visualize the “Two Chicagos”. Members form dense clusters in the <strong>central Loop and transit corridors</strong>, while casual riders are heavily concentrated along the <strong>lakefront and tourist landmarks</strong>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Geographic plot with focus on Chicago coordinates</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>all_trips_v2 <span class="sc">|&gt;</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(start_lat)) <span class="sc">|&gt;</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(start_lat <span class="sc">&gt;</span> <span class="fl">41.7</span> <span class="sc">&amp;</span> start_lat <span class="sc">&lt;</span> <span class="fl">42.05</span> <span class="sc">&amp;</span> start_lng <span class="sc">&gt;</span> <span class="sc">-</span><span class="fl">87.75</span> <span class="sc">&amp;</span> start_lng <span class="sc">&lt;</span> <span class="sc">-</span><span class="fl">87.55</span>) <span class="sc">|&gt;</span> </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> start_lng, <span class="at">y =</span> start_lat, <span class="at">color =</span> member_casual)) <span class="sc">+</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>, <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>member_casual) <span class="sc">+</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span> </span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Geographic Usage Clusters in Chicago"</span>,</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Spatial divide: Casuals (Lakefront) vs Members (Loop/Transit) "</span>,</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Data Source: Motivate International Inc."</span>,</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"User Type"</span>) <span class="sc">+</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"casual"</span> <span class="ot">=</span> <span class="st">"#F8766D"</span>, <span class="st">"member"</span> <span class="ot">=</span> <span class="st">"#00BFC4"</span>)) <span class="sc">+</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="fu">guide_legend</span>(<span class="at">override.aes =</span> <span class="fu">list</span>(<span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">3</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/visual-geographic-map-final-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 5. Spatial distribution of trip starts, reconstructing Chicago’s geography through usage density.</figcaption>
</figure>
</div>
</div>
</div>
<div class="map-container">
<iframe src="https://www.google.com/maps/d/u/0/embed?mid=1nD8INEDXijpqi46qh8JIxTnFKQ34oHg&amp;ehbc=2E312F" width="640" height="480">
</iframe>
</div>
<blockquote class="blockquote">
<p><strong>Analyst Note:</strong> The visual evidence is conclusive. When comparing the data clusters to the functional city map, we find that <strong>Casual riders</strong> are geographically “locked” to leisure corridors like <strong>Navy Pier (Streeter Dr &amp; Grand Ave)</strong> and the <strong>Museum Campus (Shedd Aquarium)</strong>. Conversely, <strong>Members</strong> are concentrated in the city’s “nervous system”—the transit hubs near <strong>Union and Ogilvie Stations (e.g., Canal St &amp; Adams St)</strong> that facilitate the daily professional commute.</p>
</blockquote>
</section>
</section>
<section id="act-recommendations" class="level2">
<h2 class="anchored" data-anchor-id="act-recommendations">6. Act (Recommendations)</h2>
<p>The following strategic recommendations are designed to convert casual riders into annual members by addressing the specific behavioral and geographic gaps identified in this analysis.</p>
<section id="localized-leisure-corridor-campaigns" class="level3">
<h3 class="anchored" data-anchor-id="localized-leisure-corridor-campaigns">6.1 Localized “Leisure Corridor” Campaigns</h3>
<p>The geographic analysis reveals that casual riders are heavily concentrated along the lakefront, specifically at landmarks such as <strong>Streeter Dr &amp; Grand Ave (Navy Pier)</strong> and the <strong>Shedd Aquarium</strong>.</p>
<ul>
<li><strong>Recommendation:</strong> Deploy targeted marketing efforts (digital geo-fencing and physical signage) exclusively at these high-traffic leisure hubs rather than a city-wide campaign. Highlighting the long-term savings for recreational riders in these specific locations will yield higher conversion rates.</li>
</ul>
</section>
<section id="the-weekend-warrior-membership-tier" class="level3">
<h3 class="anchored" data-anchor-id="the-weekend-warrior-membership-tier">6.2 The “Weekend Warrior” Membership Tier</h3>
<p>Casual ridership share doubles on weekends, with average trip duration’s reaching nearly 40 minutes. This suggests that casual users perceive the service as a primary recreational activity rather than a daily tool.</p>
<ul>
<li><strong>Recommendation:</strong> Introduce a seasonal “Weekend Explorer” membership. By showcasing that the cost of two 40-minute weekend trips is equivalent to a monthly pass, Cyclistic can bridge the gap for users who do not yet require a full annual commute-focused membership.</li>
</ul>
</section>
<section id="off-peak-afternoon-incentives" class="level3">
<h3 class="anchored" data-anchor-id="off-peak-afternoon-incentives">6.3 Off-Peak Afternoon Incentives</h3>
<p>Through independent hourly scaling, we discovered that casual riders exhibit a strong, steady climb in activity during the afternoon (1:00 PM – 4:00 PM), peaking while members are at work.</p>
<ul>
<li><strong>Recommendation:</strong> Implement an “Afternoon Member” discount. Targeting casual riders who consistently use the system during these off-peak hours with a specialized membership rate can increase system efficiency and revenue without contributing to the existing 5:00 PM member rush.</li>
</ul>
</section>
</section>
<section id="bonus-chapter-predictive-modeling-for-conversion-from-casual-insights-to-real-time-membership-offers" class="level2">
<h2 class="anchored" data-anchor-id="bonus-chapter-predictive-modeling-for-conversion-from-casual-insights-to-real-time-membership-offers">Bonus Chapter: Predictive Modeling for Conversion — From Casual Insights to Real-Time Membership Offers</h2>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>